all:
  hosts:

    local:
      ansible_connection: local

    centos6:
      vagrant_os: "bento/centos-6.10"
      hostname: "centos6"
      ansible_host: 10.0.2.20

    centos7:
      vagrant_os: "centos-7"
      hostname: "centos7"
      ansible_host: 10.0.2.21

    centos8:
      vagrant_os: "centos-8"
      hostname: "centos8"
      ansible_host: 10.0.2.22

    ubuntu1404:
      vagrant_os: "ubuntu/trusty64"
      hostname: "ubuntu1404"
      ansible_host: 10.0.2.23

    ubuntu1604:
      vagrant_os: "ubuntu/xenial64"
      hostname: "ubuntu1604"
      ansible_host: 10.0.2.24

    ubuntu1804:
      vagrant_os: "ubuntu/bionic64"
      hostname: "ubuntu1804"
      ansible_host: 10.0.2.25

    ubuntu2004:
      vagrant_os: "ubuntu/focal64"
      hostname: "ubuntu2004"
      ansible_host: 10.0.2.26

    ubuntu2010:
      vagrant_os: "ubuntu/groovy64"
      hostname: "ubuntu2010"
      ansible_host: 10.0.2.27

    amazonlinux2:
      vagrant_os: "bento/amazonlinux-2"
      hostname: "amazonlinux2"
      ansible_host: 10.0.2.28

    sles12:
      vagrant_os: "elastic/sles-12-x86_64"
      hostname: "sles12"
      ansible_host: 10.0.2.29